### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by outlace** [rosinality/knotter#2]
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/zt/qjk01pyj4hn34zyhq9h50r1c0000gn/T/pip-build-zXfvwJ/knotter

**Comment by rosinality** [comment]
Hmm I don't found any error in running egg_info command. Can you show me a full error messages or elaborate your situations?

**Comment by outlace** [comment]
Brandons-MacBook-Air:~ brandon$ pip install knotter
Collecting knotter
  Downloading knotter-0.2.0.tar.gz (750kB)
    100% |████████████████████████████████| 757kB 648kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zt/qjk01pyj4hn34zyhq9h50r1c0000gn/T/pip-build-ym27_6ob/knotter/setup.py", line 7, in <module>
        with open(path.join(here, 'DESCRIPTION.rst'), encoding='utf-8') as f:
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/zt/qjk01pyj4hn34zyhq9h50r1c0000gn/T/pip-build-ym27_6ob/knotter/DESCRIPTION.rst'

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/zt/qjk01pyj4hn34zyhq9h50r1c0000gn/T/pip-build-ym27_6ob/knotter/

**Comment by outlace** [comment]
Also, what is the roadmap for this project? Looks like its no longer in active development. From the screenshot it looks amazing, better than Ayasdi. I've been looking for a user-friendly TDA tool for a long time, Python Mapper is just not particularly usable.

**Comment by rosinality** [comment]
Aaargh I got it. This (0c2985cf80590554b24b5c6d2cda050a1ddf5243) will resolve an issue.

I think Ayasdi would offer better functionalities than Knotter. I wanted to explore potentials of TDA for data analysis. But Ayasdi don't offer free or demo version of their tools, so I made this.

Maybe porting to ipywidgets or bokeh as suggested in #1 is way-to-go, but these are seem to be more complicated than I thought (especially bokeh). Anyway I will develop this occasionally.

**Comment by outlace** [comment]
That fixed it. Can you upload a test data set? I'm not able to get it working with my own data. I browse -> select CSV -> select the columns I want -> modify parameters -> click Analyze and it does nothing

**Comment by rosinality** [comment]
https://github.com/rosinality/knotter/blob/master/samples/swiss-roll.csv (came from manifold learning example of scikit-learn, http://scikit-learn.org/stable/auto_examples/manifold/plot_compare_methods.html) Maybe you can start with this. Select variable x, y, z, and by adjusting number of covers/overlap you can get analysis result. Also you can color the graph by toggle color panel (palette icon) and select variable color.

**Comment by outlace** [comment]
This is fantastic. Exactly the user-friendly TDA tool I was looking for. I'd like to help contribute to this project to get it to a point where academic researchers could use it in production. Do you think this can scale with big data sets? I notice it lags and gets slow analyzing my data. Is it possible to utilize the GPU for this analysis?

**Comment by rosinality** [comment]
Maybe I should clean the code first...:)

I experienced that most slowdown came from current simple and crude find_nerve functions. I will revise it so that it will run more fast especially when # of cover is large. (current algorithm searches (# of clusters combination 2) pairs)
GPU can be used in clustering step, but fastcluster of hdbscan can be tried first. Maybe hdbscan is better choice than hierarchical clustering when # of data points is enough large.
Another problems is that memory consumption came from pairwise distance matrices. But fixing this will be more difficult than computation-wise speed-ups.

**Comment by mlnjsh** [comment]
I have installed knotter in Anaconda but i am not able to start it...how do i start it

**Comment by rosinality** [comment]
Can I get an error message?

**Comment by mlnjsh** [comment]
I am not able to start Knotter

showing Syntax error

after installing it in anaconda i type

>>> knotter

it says syntax error and moerover i dont know how to initiate it..



regards

**Comment by rosinality** [comment]
I tested, but I cannot find syntax error...can you give me an error message?
