### ISSUE TITLE
Error and not able to launch using OSX Anaconda

### ISSUE THREAD

**Issue by tomtomato** [rosinality/knotter#5]
I'm getting the following when trying to run knotter.  Mac OSX 10.12.5 using Anaconda python 3.6.  Latest version of knotter installed with pip:

```
$ knotter
Serving at port 8000
Server started at http://localhost:9000
0:30: execution error: "localhost:8000" doesn’t understand the “open location” message. (-1708)
```

At first I thought the problem was that Firefox was not up to date, because after updating Firefox I did manage to get the GUI window once.  However, since that one time I am now getting the above error again each time I run knotter.

**Comment by tomtomato** [comment]
My Firefox was out of date.  Updated Firefox and it's all good.

**Comment by rosinality** [comment]
Fixed in 8641a03a83d9677628a1e383b21b29243dc7fc75

**Comment by tomtomato** [comment]
Thanks!  It now works and I am able to run the test dataset.  This looks very nice!

How do I define groups?  When I click the Comparing button and add groups, all groups have 0 nodes and 0 points?

Also, a few errors are showing up in terminal.  When I start knotter, I get the following error, but everything launches fine in Chrome:

```
$ knotter
Serving at port 8000
Server started at http://localhost:9000
0:37: execution error: "http://localhost:8000" doesn’t understand the “open location” message. (-1708)
```
The following error also shows up at the end in terminal:

```
Traceback (most recent call last):
  File "/Users/novak/anaconda/lib/python3.6/site-packages/knotter/server.py", line 484, in handler
    self.event_map[data['type']](data)
  File "/Users/novak/anaconda/lib/python3.6/site-packages/knotter/server.py", line 386, in read_data
    self.analyzer.load_dataframe(data['content'])
  File "/Users/novak/anaconda/lib/python3.6/site-packages/knotter/server.py", line 34, in load_dataframe
    self.df = pd.read_csv(data_io)
  File "/Users/novak/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/novak/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 411, in _read
    data = parser.read(nrows)
  File "/Users/novak/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 982, in read
    ret = self._engine.read(nrows)
  File "/Users/novak/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 1719, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 890, in pandas._libs.parsers.TextReader.read (pandas/_libs/parsers.c:10862)
  File "pandas/_libs/parsers.pyx", line 912, in pandas._libs.parsers.TextReader._read_low_memory (pandas/_libs/parsers.c:11138)
  File "pandas/_libs/parsers.pyx", line 966, in pandas._libs.parsers.TextReader._read_rows (pandas/_libs/parsers.c:11884)
  File "pandas/_libs/parsers.pyx", line 953, in pandas._libs.parsers.TextReader._tokenize_rows (pandas/_libs/parsers.c:11755)
  File "pandas/_libs/parsers.pyx", line 2184, in pandas._libs.parsers.raise_parser_error (pandas/_libs/parsers.c:28765)
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 110, saw 3
```

**Comment by rosinality** [comment]
Maybe you can refer to this document: https://github.com/rosinality/knotter/blob/master/docs/tutorial.md You can define groups by right-click-and-drag. By this you can select point/nodes in the workspace.

It seems like that execution error is related to OS X. I thought it is fixed in 8641a03a83d9677628a1e383b21b29243dc7fc75 but it seems like that it is incomplete. Currently I don't know exact reason of this, so I will solve this problem when I find the reason. Anyway, it is only related to the auto browser-opening functionality, so rest will work without a problem if you manually open the page.

And rest error is related to read csv file (from pandas). Maybe there are some problems in your data. Can you check 110th line of your csv file?

**Comment by tomtomato** [comment]
Thanks for pointing that out!  Part of my problem is my Mac trackpad was sent to two-finger tap for right-click.  I changed that to bottom left of corner of the trackpad for right-click, and I can now right-click-and-drag.  

However, I noticed another issue.  In Chrome (Mac Sierra) I see the dashed black rectangular outlines appear, but no group is created.  The group stays at 0 nodes and 0 points.  When I use Firefox, though, everything works properly.  The dashed black outline appears and a number is shown for nodes and points for the group.  So, I can get the group generation working if I use Firefox, but not Chrome.

**Comment by rosinality** [comment]
I mainly tested using Safari and Firefox. I will test behaviors in Chrome.
