### ISSUE TITLE
Logistic Regression Fails To Run 

### ISSUE THREAD

**Issue by NickHogan** [rosinality/knotter#7]
Below error is triggered when calling Logistic regression in Ubuntu. 

Love the package by the way

Traceback (most recent call last):
  File "/home/braincreator/virtualenvs/tda_env/lib/python3.5/site-packages/knotter/server.py", line 484, in handler
    self.event_map[data['type']](data)
  File "/home/braincreator/virtualenvs/tda_env/lib/python3.5/site-packages/knotter/server.py", line 407, in compare_node
    headers, rows = self.analyzer.descriptive_compare(data['group'])
  File "/home/braincreator/virtualenvs/tda_env/lib/python3.5/site-packages/knotter/server.py", line 301, in descriptive_compare
    table.append(np.vstack(sub_col).T)
  File "/home/braincreator/virtualenvs/tda_env/lib/python3.5/site-packages/numpy/core/shape_base.py", line 234, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate

**Comment by rosinality** [comment]
Sorry, logistic regression is not implemented yet...

**Comment by NickHogan** [comment]
In that case is it possible to display a selected groups standard error by variable next to the mean in the analysis page?

**Comment by rosinality** [comment]
Yes, I'll implement the features soon.

**Comment by rosinality** [comment]
Added in ed0f7eb60ba19aa8549be5712ca7a48b578da88c
